// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package httpjson

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HTTPJSONServiceClient is the client API for HTTPJSONService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HTTPJSONServiceClient interface {
	Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error)
}

type hTTPJSONServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHTTPJSONServiceClient(cc grpc.ClientConnInterface) HTTPJSONServiceClient {
	return &hTTPJSONServiceClient{cc}
}

func (c *hTTPJSONServiceClient) Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error) {
	out := new(HandleResponse)
	err := c.cc.Invoke(ctx, "/httpjson.v1.HTTPJSONService/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPJSONServiceServer is the server API for HTTPJSONService service.
// All implementations must embed UnimplementedHTTPJSONServiceServer
// for forward compatibility
type HTTPJSONServiceServer interface {
	Handle(context.Context, *HandleRequest) (*HandleResponse, error)
	mustEmbedUnimplementedHTTPJSONServiceServer()
}

// UnimplementedHTTPJSONServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHTTPJSONServiceServer struct {
}

func (UnimplementedHTTPJSONServiceServer) Handle(context.Context, *HandleRequest) (*HandleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedHTTPJSONServiceServer) mustEmbedUnimplementedHTTPJSONServiceServer() {}

// UnsafeHTTPJSONServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HTTPJSONServiceServer will
// result in compilation errors.
type UnsafeHTTPJSONServiceServer interface {
	mustEmbedUnimplementedHTTPJSONServiceServer()
}

func RegisterHTTPJSONServiceServer(s grpc.ServiceRegistrar, srv HTTPJSONServiceServer) {
	s.RegisterService(&HTTPJSONService_ServiceDesc, srv)
}

func _HTTPJSONService_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPJSONServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/httpjson.v1.HTTPJSONService/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPJSONServiceServer).Handle(ctx, req.(*HandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HTTPJSONService_ServiceDesc is the grpc.ServiceDesc for HTTPJSONService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HTTPJSONService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "httpjson.v1.HTTPJSONService",
	HandlerType: (*HTTPJSONServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _HTTPJSONService_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "httpjson.proto",
}
